// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Export(arg1:string,arg2:core.ExportOptions):Promise<core.ExportResult>;

export function Generate(arg1:core.GenerateParams):Promise<core.GenerateResult>;

export function GetPaperSpecs(arg1:core.SpecQuery):Promise<core.PaperSpecCatalog>;

export function GetPhotoSpecs(arg1:core.SpecQuery):Promise<core.PhotoSpecCatalog>;

export function GetRemoteStatus():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function LoadImage(arg1:string):Promise<core.LoadImageResult>;

export function OpenImageDialog():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetCurrentPaperSpec(arg1:string):Promise<void>;

export function SetCurrentPhotoSpec(arg1:string):Promise<void>;

export function StartRemoteServer(arg1:number):Promise<Record<string, any>>;

export function StopRemoteServer():Promise<void>;
