// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Export(arg1:string,arg2:core.ExportOptions):Promise<core.ExportResult>;

export function Generate(arg1:core.GenerateParams):Promise<core.GenerateResult>;

export function GetFaceDetectModels(arg1:core.SpecQuery):Promise<core.ModelCatalog>;

export function GetMattingModels(arg1:core.SpecQuery):Promise<core.ModelCatalog>;

export function GetPaperSpecs(arg1:core.SpecQuery):Promise<core.PaperSpecCatalog>;

export function GetPhotoSpecs(arg1:core.SpecQuery):Promise<core.PhotoSpecCatalog>;

export function GetRemoteStatus():Promise<Record<string, any>>;

export function GetWatermarkConfig():Promise<core.WatermarkConfigResult>;

export function Greet(arg1:string):Promise<string>;

export function ListPrinters():Promise<Array<core.PrinterInfo>>;

export function LoadImage(arg1:string):Promise<core.LoadImageResult>;

export function OpenImageDialog():Promise<string>;

export function PrintLayout(arg1:core.PrintOptions):Promise<core.PrintResult>;

export function SelectFolder():Promise<string>;

export function SetCurrentFaceDetectModel(arg1:string):Promise<void>;

export function SetCurrentMattingModel(arg1:string):Promise<void>;

export function SetCurrentPaperSpec(arg1:string):Promise<void>;

export function SetCurrentPhotoSpec(arg1:string):Promise<void>;

export function SetWatermarkConfig(arg1:core.WatermarkSettings):Promise<void>;

export function StartRemoteServer(arg1:number):Promise<Record<string, any>>;

export function StopRemoteServer():Promise<void>;
