// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1, arg2) {
  return window['go']['main']['App']['Export'](arg1, arg2);
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GetFaceDetectModels(arg1) {
  return window['go']['main']['App']['GetFaceDetectModels'](arg1);
}

export function GetMattingModels(arg1) {
  return window['go']['main']['App']['GetMattingModels'](arg1);
}

export function GetPaperSpecs(arg1) {
  return window['go']['main']['App']['GetPaperSpecs'](arg1);
}

export function GetPhotoSpecs(arg1) {
  return window['go']['main']['App']['GetPhotoSpecs'](arg1);
}

export function GetRemoteStatus() {
  return window['go']['main']['App']['GetRemoteStatus']();
}

export function GetWatermarkConfig() {
  return window['go']['main']['App']['GetWatermarkConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListPrinters() {
  return window['go']['main']['App']['ListPrinters']();
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}

export function PrintLayout(arg1) {
  return window['go']['main']['App']['PrintLayout'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetCurrentFaceDetectModel(arg1) {
  return window['go']['main']['App']['SetCurrentFaceDetectModel'](arg1);
}

export function SetCurrentMattingModel(arg1) {
  return window['go']['main']['App']['SetCurrentMattingModel'](arg1);
}

export function SetCurrentPaperSpec(arg1) {
  return window['go']['main']['App']['SetCurrentPaperSpec'](arg1);
}

export function SetCurrentPhotoSpec(arg1) {
  return window['go']['main']['App']['SetCurrentPhotoSpec'](arg1);
}

export function SetWatermarkConfig(arg1) {
  return window['go']['main']['App']['SetWatermarkConfig'](arg1);
}

export function StartRemoteServer(arg1) {
  return window['go']['main']['App']['StartRemoteServer'](arg1);
}

export function StopRemoteServer() {
  return window['go']['main']['App']['StopRemoteServer']();
}
